import imagen from "../assets/img/auris.sennheiser.jpg"
import imagen2 from "../assets/img/auris.aiaiai.jpg"
import imagen3 from "../assets/img/auris.technics.jpg"
import imagen4 from "../assets/img/auris.pioneer.jpg"
import imagen5 from "../assets/img/monitores.krk.jpg"
import imagen6 from "../assets/img/monitores.jbl.jpg"
import imagen7 from "../assets/img/monitores.yamaha.jpg"
import imagen8 from "../assets/img/monitores.pioneer.jpg"
import imagen9 from "../assets/img/mixer.450.jpg"
import imagen10 from "../assets/img/mixer.900.jpg"
import imagen11 from "../assets/img/mixer.23c.jpg"
import imagen12 from "../assets/img/mixer.92.jpg"
import imagen13 from "../assets/img/compacteras.700.jpg"
import imagen14 from "../assets/img/compacteras.1000.jpg"
import imagen15 from "../assets/img/compacteras.2000.jpg"
import imagen16 from "../assets/img/compacteras.3000.jpg"

const products = [
    { id: 1, categoria: "Auriculares", marca: "Sennheiser", modelo:"HD 25", descripcion: "Sennheiser HD 25 auriculares de estudio. Diseñados para aplicaciones de monitoreo profesional, los auriculares HD 25 ofrecen una excelente atenuación del ruido ambiente.", stock: 8, precioTarjeta: 55000, precioEfectivo: 52000, imagen: imagen, ruta: "auriculares"},
    { id: 2, categoria: "Auriculares", marca: "AIAIAI", modelo:"Dj Preset", descripcion: "Este preset se ha configurado con la unidad de altavoz S02 titanio recubierto que ofrece una representación sonora impactante e intenso ampliando la dinámica de bajos y de gama baja . La combinación de la cinta de nylon H02 durable y las almohadillas de cuero E02, proporciona un gran aislamiento, este es un audífono robusto, adecuado para actuaciones en directo, de música con altos bajos o pesada.", stock: 10, precioTarjeta: 52000, precioEfectivo: 49000, imagen: imagen2, ruta: "auriculares"},
    { id: 3, categoria: "Auriculares", marca: "Technics", modelo:"Dj 1200", descripcion: "El Technics - EAH-DJ1200 es el sucesor del legendario auricular para DJ RP-DJ1200. Los auriculares para DJ Profi-On-Ear cuentan con un controlador de nuevo desarrollo con una potente bobina de voz CAW de 40 mm para un sonido excepcional, que se reproduce de forma clara y detallada incluso a volúmenes ambientales muy altos. Además, el EAH-DJ1200 plegable ofrece una excelente funcionalidad y durabilidad para uso profesional de DJ.", stock: 5, precioTarjeta: 48000, precioEfectivo: 45000, imagen: imagen3, ruta: "auriculares"},
    { id: 4, categoria: "Auriculares", marca: "Pioneer", modelo:"HDJ-X5", descripcion: "Los auriculares HDJ-X están diseñados para ser flexibles. Su mecanismo de giro te permite usarlos cómodamente, según tus preferencias, durante largos períodos de tiempo. No te preocupes por pequeñas caídas y golpes durante el transporte, ya que estos auriculares DJ están preparados para su uso prolongado y en condiciones severas.", stock: 3, precioTarjeta: 42000, precioEfectivo: 40000, imagen: imagen4, ruta: "auriculares"},
    { id: 5, categoria: "Monitores de Estudio", marca: "KRK", modelo:"Rokit 5", descripcion: "Los monitores ROKIT 5 de KRK son monitores de estudio amplificados que ofrecen un rendimiento profesional y precisión para la grabación, mezcla, masterización y reproducción.", stock: 12, precioTarjeta: 78000, precioEfectivo: 74000, imagen: imagen5, ruta: "monitores-de-estudio"},
    { id: 6, categoria: "Monitores de Estudio", marca: "JBL", modelo:"LSR 305 MK2", descripcion: "JBL 305P MKII es un monitor activo bi-amplificado de estudio de 5 pulgadas. Incorpora el sitema JBL Image Control y transductores profesionales. JBL 305P MkII ofrece detalles asombrosos, imágenes precisas y un rango dinámico impresionante que mejora las capacidades de escucha críticas de cualquier espacio de trabajo. Con tecnologías patentadas derivadas de los monitores de referencia maestros MBL Serie 7 y M2, y con un diseño elegante y moderno, JBL 305P MkII ofrece un rendimiento excepcional y una experiencia de mezcla y producción agradable a un precio accesible. ", stock: 8, precioTarjeta: 96000, precioEfectivo: 91000, imagen: imagen6, ruta: "monitores-de-estudio"},
    { id: 7, categoria: "Monitores de Estudio", marca: "Yamaha", modelo:"HS5", descripcion: "Monitor de estudio de 2 vías y campo cercano, bass-reflex biamplificado, con woofer de cono de 5 pulgadas y tweeter de cúpula de 1 pulgada.", stock: 4, precioTarjeta: 98000, precioEfectivo: 93000, imagen: imagen7, ruta: "monitores-de-estudio"},
    { id: 8, categoria: "Monitores de Estudio", marca: "Pioneer", modelo:"S-DJ50X", descripcion: "Los altavoces activos de referencia S-DJ están diseñados para ofrecer un sonido neutral preciso y excelente flexibilidad a productores y DJs profesionales. Tanto si estás pinchando, produciendo música o escuchando pistas, los S-DJ reproducen fielmente la fuente original - mientras que el EQ lineal te permite ajustar con precisión las frecuencias según sea necesario.", stock: 6, precioTarjeta: 82000, precioEfectivo: 78000, imagen:imagen8, ruta: "monitores-de-estudio"},
    { id: 9, categoria: "Mixer", marca: "Pioneer", modelo:"DJM-450MK2", descripcion: "Con muchas de las características heredadas de la DJM-900NXS2es la mesa de mezclas ideal para complementar a los reproductores XDJ-700 o los platos PLX-1000. El crossfader Magvel, el suave EQ y los faders de canal ofrecen una respuesta precisa para que te sientas seguro mezclando. Mientras que Sound Colour FX y Beat FX, con control de parámetros, añaden un toque creativo a tus mezclas. Y gracias al procesador digital de 64 bits disfrutarás de audio de alta calidad, cálido, tanto para las fuentes de sonido analógicas como la digitales.", stock: 5, precioTarjeta: 119000, precioEfectivo: 113000, imagen: imagen9, ruta: "mixers"},
    { id: 10, categoria: "Mixer", marca: "Pioneer", modelo:"DJM-900NXS2", descripcion: "Lleva tu actuación a un nuevo nivel con la DJM-900NXS2, que cuenta con nuestro primer procesador de mezclas de 64 bits para un sonido más cálido, más matizado. Hemos ajustado con precisión las curvas de ecualización y el fader y mejorado los controles FX para darte más opciones creativas. Además, la versátil DJM-900NXS2 tiene un Send/Return independiente, 4 entradas phono y 2 puertos USB, permitiéndote configurarlo a tu manera.", stock: 3, precioTarjeta: 367000, precioEfectivo: 349000, imagen: imagen10, ruta: "mixers"},
    { id: 11, categoria: "Mixer", marca: "Allen & Heath", modelo:"Xone 23C", descripcion: "Este mezclador para DJ de alto rendimiento está equipado con una tarjeta de sonido interna de 4 canales de 96 kHz y 24 bits de estéreo de alta calidad y ofrece conexión plug and play a través de X: LINK a los controladores de la serie Xone: K, lo que la hace perfecta para los intérpretes que buscan combinar la conveniencia del DJ digital. y grabación con el control práctico y el atractivo visual de un mezclador real.", stock: 7, precioTarjeta: 129000, precioEfectivo: 122000, imagen: imagen11, ruta: "mixers"},
    { id: 12, categoria: "Mixer", marca: "Allen & Heath", modelo:"Xone 92", descripcion: "El Xone: 23C reúne lo mejor del DJ digital y la mezcla convencional en un formato compacto y accesible. Este mezclador para DJ de alto rendimiento está equipado con una tarjeta de sonido interna de 4 canales de 96 kHz y 24 bits de estéreo de alta calidad y ofrece conexión plug and play a través de X: LINK a los controladores de la serie Xone: K, lo que la hace perfecta para los intérpretes que buscan combinar la conveniencia del DJ digital. y grabación con el control práctico y el atractivo visual de un mezclador real. Xone: 23C incluye una versión mejorada del legendario filtro Xone con control de resonancia, faders VCA, EQ de interrupción total de 3 bandas, interruptores iluminados, selector de curva de crossfader y estilo inspirado en el modelo insignia Xone: DB4.", stock: 4, precioTarjeta: 467000, precioEfectivo: 444000, imagen: imagen12, ruta: "mixers"},
    { id: 13, categoria: "Reproductor Digital Dj", marca: "Pioneer", modelo:"XDJ-700", descripcion: "El XDJ-700 dispone de una gran pantalla táctil, y un diseño familiar con funciones heredadas de su hermano mayor, el XDJ-1000. Su tamaño compacto y su soporte extraíble lo hace perfecto para cabinas pequeñas o espacios reducidos en casa.", stock: 8, precioTarjeta: 201000, precioEfectivo: 191000, imagen: imagen13, ruta: "reproductores-dj"},
    { id: 14, categoria: "Reproductor Digital Dj", marca: "Pioneer", modelo:"XDJ-1000MK2", descripcion: "Basado en su predecesor, el XDJ-1000MK2 mejora la usabilidad con la navegación a través de la pista mejorada y soporte para archivos de audio de alta resolución FLAC y ALAC. Hereda el gran jog wheel y la pantalla táctil a todo color de 7 pulgadas del CDJ-2000NXS2, también características como 8 Hot Cues y Quantize.", stock: 6, precioTarjeta: 330000, precioEfectivo: 314000, imagen: imagen14, ruta: "reproductores-dj"},
    { id: 15, categoria: "Reproductor Digital Dj", marca: "Pioneer", modelo:"CDJ-2000NX2", descripcion: "El CDJ-2000NXS2 hereda todas las mejores características de su predecesor – el CDJ-2000NXS – y da un gran paso adelante. Hemos añadido una gran pantalla táctil multicolor con un teclado QWERTY y filtros de búsqueda para ayudarte a seleccionar las pistas más rápido. 2 bancos de 4 Hot Cues te dan más libertad creativa, mientras que una tarjeta de sonido de 96 kHz/24-bit y soporte para FLAC/Apple Lossless Audio (ALAC) te permite reproducir formatos de mayor resolución.", stock: 4, precioTarjeta: 551000, precioEfectivo: 523000, imagen: imagen15, ruta: "reproductores-dj"},
    { id: 16, categoria: "Reproductor Digital Dj", marca: "Pioneer", modelo:"CDJ-3000", descripcion: "Mejora tu poder creativo con nuestro multireproductor avanzado, el CDJ-3000. Esta robusta unidad está alimentada por un nuevo MPU y está equipada con componentes de alta calidad especialmente desarrollados y características innovadoras.", stock: 2, precioTarjeta: 750000, precioEfectivo: 714000, imagen: imagen16, ruta: "reproductores-dj"},
]; //

export const getFetch = new Promise ((resolve)=>{
    setTimeout(()=>{
        resolve(products)
    }, 2000)
})